server:
  port: 8080

spring:
  application:
    name: AnimecixNotifier

  mongodb:
    uri: mongodb://casper:27017/animecix-db


logging:
  level:
    root: info

client:
  animecix: https://animecix.tv