server:
  port: 8080

spring:
  application:
    name: AnimecixNotifier

  main:
    allow-bean-definition-overriding: true

  mongodb:
    uri: mongodb://casper:27017/animecix-db

  threads:
    virtual:
      enabled: true

logging:
  level:
    root: info

client:
  animecix: https://animecix.tv